import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ArrowDownLeft,
  ArrowUpRight,
  CreditCard,
  Loader2,
  RefreshCw,
  Wallet,
  Webhook,
} from "lucide-react";
import { useTranslation } from "react-i18next";

import { API } from "@/api";
import type {
  BillingAdminOverview,
  BillingCheckoutConfig,
  BillingTransaction,
  GetSystemConfigResponse,
  SystemConfigPatch,
} from "@/types";
import { useAppStore } from "@/stores/app-store";

const BILLING_COPY = {
  en: {
    title: "Billing and recharge",
    subtitle: "Operate the prepaid wallet, configure Stripe, and review the ledger generated by real API usage.",
    stripeTitle: "Stripe hosted checkout",
    stripeBody: "Use Stripe Checkout Sessions for real card payments, then credit the wallet through a verified webhook.",
    secretKeyLabel: "Stripe secret key",
    webhookSecretLabel: "Stripe webhook secret",
    publicUrlLabel: "Public app URL",
    publicUrlHint: "Used for success/cancel return URLs. Leave empty to fall back to the current origin.",
    saveStripe: "Save Stripe config",
    savingStripe: "Saving Stripe config...",
    clearSaved: "Clear saved",
    currentSaved: "Current",
    stripeReady: "Checkout ready",
    stripeNotReady: "Checkout disabled until secret key and webhook secret are both configured.",
    webhookEndpoint: "Webhook endpoint",
    rechargeTitle: "Manual recharge",
    rechargeBody: "Pick a user, choose a currency bucket, and add funds to the prepaid balance.",
    userLabel: "User",
    currencyLabel: "Currency",
    amountLabel: "Amount",
    noteLabel: "Note",
    notePlaceholder: "Optional operator note",
    submit: "Add recharge",
    submitting: "Recharging...",
    refresh: "Refresh",
    balancesTitle: "User balances",
    balancesEmpty: "No users found.",
    transactionsTitle: "Recent ledger",
    transactionsEmpty: "No billing transactions yet.",
    success: "Recharge added.",
    stripeSaved: "Stripe configuration saved.",
    stripeCleared: "Saved Stripe field cleared.",
  },
  zh: {
    title: "充值计费",
    subtitle: "统一管理预付费钱包、Stripe 实付配置，以及按真实 API 成本回写的账本流水。",
    stripeTitle: "Stripe 托管收银台",
    stripeBody: "通过 Stripe Checkout Session 发起真实银行卡支付，到账后由 webhook 验签并幂等入账。",
    secretKeyLabel: "Stripe Secret Key",
    webhookSecretLabel: "Stripe Webhook Secret",
    publicUrlLabel: "公网应用地址",
    publicUrlHint: "用于成功/取消回跳地址。留空时会回退到当前站点 origin。",
    saveStripe: "保存 Stripe 配置",
    savingStripe: "正在保存 Stripe 配置...",
    clearSaved: "清除已保存",
    currentSaved: "当前",
    stripeReady: "结账链路已就绪",
    stripeNotReady: "只有 Secret Key 和 Webhook Secret 都配置好后，用户侧才能发起真实支付。",
    webhookEndpoint: "Webhook 地址",
    rechargeTitle: "手动充值",
    rechargeBody: "为指定用户的预付费余额补充资金，系统自动扣费仍然写入同一套账本。",
    userLabel: "用户",
    currencyLabel: "币种",
    amountLabel: "金额",
    noteLabel: "备注",
    notePlaceholder: "可选，记录本次充值说明",
    submit: "确认充值",
    submitting: "充值中...",
    refresh: "刷新",
    balancesTitle: "用户余额",
    balancesEmpty: "当前还没有可展示的用户。",
    transactionsTitle: "最近流水",
    transactionsEmpty: "账本里还没有充值或扣费记录。",
    success: "充值已入账。",
    stripeSaved: "Stripe 配置已保存。",
    stripeCleared: "已清除保存的 Stripe 字段。",
  },
} as const;

type BillingLocale = keyof typeof BILLING_COPY;

type StripeSettingsState = {
  publicAppUrl: string;
  secretKeyMasked: string | null;
  secretKeyIsSet: boolean;
  webhookSecretMasked: string | null;
  webhookSecretIsSet: boolean;
};

function useBillingLocale(): BillingLocale {
  const { i18n } = useTranslation();
  return (i18n.resolvedLanguage ?? i18n.language ?? "").startsWith("zh") ? "zh" : "en";
}

function useBillingCopy() {
  return BILLING_COPY[useBillingLocale()];
}

function formatMoney(amount: number, currency: string, locale: BillingLocale): string {
  try {
    return new Intl.NumberFormat(locale === "zh" ? "zh-CN" : "en-US", {
      style: "currency",
      currency,
      minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
      maximumFractionDigits: 4,
    }).format(amount);
  } catch {
    return `${amount.toFixed(4)} ${currency}`;
  }
}

function formatSignedAmount(tx: BillingTransaction, locale: BillingLocale): string {
  const sign = tx.amount > 0 ? "+" : "";
  return `${sign}${formatMoney(tx.amount, tx.currency, locale)}`;
}

function toStripeSettings(config: GetSystemConfigResponse): StripeSettingsState {
  return {
    publicAppUrl: config.settings.public_app_url ?? "",
    secretKeyMasked: config.settings.stripe_secret_key.masked,
    secretKeyIsSet: config.settings.stripe_secret_key.is_set,
    webhookSecretMasked: config.settings.stripe_webhook_secret.masked,
    webhookSecretIsSet: config.settings.stripe_webhook_secret.is_set,
  };
}

export function BillingSection() {
  const copy = useBillingCopy();
  const locale = useBillingLocale();
  const pushToast = useAppStore((state) => state.pushToast);

  const [overview, setOverview] = useState<BillingAdminOverview | null>(null);
  const [checkoutConfig, setCheckoutConfig] = useState<BillingCheckoutConfig | null>(null);
  const [stripeSettings, setStripeSettings] = useState<StripeSettingsState>({
    publicAppUrl: "",
    secretKeyMasked: null,
    secretKeyIsSet: false,
    webhookSecretMasked: null,
    webhookSecretIsSet: false,
  });
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [savingStripe, setSavingStripe] = useState(false);
  const [selectedUserId, setSelectedUserId] = useState("");
  const [currency, setCurrency] = useState("USD");
  const [amount, setAmount] = useState("");
  const [note, setNote] = useState("");
  const [stripeDraft, setStripeDraft] = useState({
    secretKey: "",
    webhookSecret: "",
    publicAppUrl: "",
  });

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [nextOverview, nextSystemConfig, nextCheckoutConfig] = await Promise.all([
        API.getBillingAdminOverview(),
        API.getSystemConfig(),
        API.getBillingCheckoutConfig(),
      ]);

      setOverview(nextOverview);
      setSelectedUserId((current) => {
        if (current && nextOverview.users.some((user) => user.user_id === current)) {
          return current;
        }
        return nextOverview.users[0]?.user_id ?? "";
      });
      setStripeSettings(toStripeSettings(nextSystemConfig));
      setStripeDraft({
        secretKey: "",
        webhookSecret: "",
        publicAppUrl: nextSystemConfig.settings.public_app_url ?? "",
      });
      setCheckoutConfig(nextCheckoutConfig);
    } catch (error) {
      pushToast((error as Error).message, "error");
    } finally {
      setLoading(false);
    }
  }, [pushToast]);

  useEffect(() => {
    void loadData();
  }, [loadData]);

  const selectedUser = useMemo(
    () => overview?.users.find((user) => user.user_id === selectedUserId) ?? null,
    [overview, selectedUserId],
  );

  const stripeDirty = Boolean(
    stripeDraft.secretKey.trim()
      || stripeDraft.webhookSecret.trim()
      || stripeDraft.publicAppUrl !== stripeSettings.publicAppUrl,
  );

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    const parsedAmount = Number(amount);
    if (!selectedUserId || !Number.isFinite(parsedAmount) || parsedAmount <= 0) {
      return;
    }

    setSubmitting(true);
    try {
      await API.createBillingTopup({
        user_id: selectedUserId,
        amount: parsedAmount,
        currency,
        note: note.trim() || undefined,
      });
      pushToast(copy.success, "success");
      setAmount("");
      setNote("");
      await loadData();
    } catch (error) {
      pushToast((error as Error).message, "error");
    } finally {
      setSubmitting(false);
    }
  };

  const handleSaveStripe = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!stripeDirty) return;

    const patch: SystemConfigPatch = {};
    if (stripeDraft.secretKey.trim()) {
      patch.stripe_secret_key = stripeDraft.secretKey.trim();
    }
    if (stripeDraft.webhookSecret.trim()) {
      patch.stripe_webhook_secret = stripeDraft.webhookSecret.trim();
    }
    if (stripeDraft.publicAppUrl !== stripeSettings.publicAppUrl) {
      patch.public_app_url = stripeDraft.publicAppUrl.trim();
    }
    if (Object.keys(patch).length === 0) return;

    setSavingStripe(true);
    try {
      const nextConfig = await API.updateSystemConfig(patch);
      const nextCheckoutConfig = await API.getBillingCheckoutConfig();
      setStripeSettings(toStripeSettings(nextConfig));
      setStripeDraft({
        secretKey: "",
        webhookSecret: "",
        publicAppUrl: nextConfig.settings.public_app_url ?? "",
      });
      setCheckoutConfig(nextCheckoutConfig);
      pushToast(copy.stripeSaved, "success");
    } catch (error) {
      pushToast((error as Error).message, "error");
    } finally {
      setSavingStripe(false);
    }
  };

  const clearStripeField = async (field: "stripe_secret_key" | "stripe_webhook_secret") => {
    setSavingStripe(true);
    try {
      const nextConfig = await API.updateSystemConfig({ [field]: "" } as SystemConfigPatch);
      const nextCheckoutConfig = await API.getBillingCheckoutConfig();
      setStripeSettings(toStripeSettings(nextConfig));
      setStripeDraft({
        secretKey: "",
        webhookSecret: "",
        publicAppUrl: nextConfig.settings.public_app_url ?? "",
      });
      setCheckoutConfig(nextCheckoutConfig);
      pushToast(copy.stripeCleared, "success");
    } catch (error) {
      pushToast((error as Error).message, "error");
    } finally {
      setSavingStripe(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center gap-2 p-6 text-sm text-[var(--sf-text-muted)]">
        <Loader2 className="h-4 w-4 animate-spin" />
        {copy.refresh}
      </div>
    );
  }

  return (
    <div className="space-y-6 p-2">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="space-y-1">
          <h3 className="text-xl font-semibold text-[var(--sf-text)]">{copy.title}</h3>
          <p className="max-w-3xl text-sm leading-7 text-[var(--sf-text-muted)]">{copy.subtitle}</p>
        </div>
        <button
          type="button"
          onClick={() => void loadData()}
          className="frametale-secondary-button inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium transition hover:-translate-y-0.5"
        >
          <RefreshCw className="h-4 w-4" />
          {copy.refresh}
        </button>
      </div>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,380px)_minmax(0,1fr)]">
        <div className="space-y-6">
          <section className="rounded-[1.6rem] border border-[rgba(117,132,159,0.18)] bg-[rgba(248,250,253,0.92)] p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-full bg-[rgba(24,151,214,0.08)] text-[var(--sf-blue)]">
                <CreditCard className="h-5 w-5" />
              </div>
              <div>
                <h4 className="text-lg font-semibold text-[var(--sf-text)]">{copy.stripeTitle}</h4>
                <p className="text-sm text-[var(--sf-text-muted)]">{copy.stripeBody}</p>
              </div>
            </div>

            <div className="mt-5 rounded-[1.2rem] border border-[rgba(117,132,159,0.18)] bg-white/85 px-4 py-3 text-sm text-[var(--sf-text-muted)]">
              <div className="font-medium text-[var(--sf-text)]">
                {checkoutConfig?.enabled ? copy.stripeReady : copy.stripeNotReady}
              </div>
              {checkoutConfig?.webhook_endpoint && (
                <div className="mt-3 break-all text-xs leading-6">
                  <span className="font-semibold uppercase tracking-[0.16em] text-[var(--sf-text-soft)]">
                    {copy.webhookEndpoint}
                  </span>
                  <div className="mt-1">{checkoutConfig.webhook_endpoint}</div>
                </div>
              )}
              {checkoutConfig?.mode && checkoutConfig.mode !== "disabled" && (
                <div className="mt-3 inline-flex rounded-full bg-[rgba(24,151,214,0.08)] px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] text-[var(--sf-blue-strong)]">
                  {checkoutConfig.mode}
                </div>
              )}
            </div>

            <form onSubmit={(event) => void handleSaveStripe(event)} className="mt-5 space-y-4">
              <label className="block">
                <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                  {copy.secretKeyLabel}
                </span>
                {stripeSettings.secretKeyIsSet && (
                  <div className="mb-2 flex items-center justify-between gap-3 text-xs text-[var(--sf-text-muted)]">
                    <span>{copy.currentSaved}: {stripeSettings.secretKeyMasked}</span>
                    <button
                      type="button"
                      onClick={() => void clearStripeField("stripe_secret_key")}
                      disabled={savingStripe}
                      className="text-[var(--sf-blue-strong)] transition hover:opacity-70 disabled:opacity-50"
                    >
                      {copy.clearSaved}
                    </button>
                  </div>
                )}
                <input
                  type="password"
                  value={stripeDraft.secretKey}
                  onChange={(event) => setStripeDraft((prev) => ({ ...prev, secretKey: event.target.value }))}
                  placeholder="sk_live_... / sk_test_..."
                  className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                  {copy.webhookSecretLabel}
                </span>
                {stripeSettings.webhookSecretIsSet && (
                  <div className="mb-2 flex items-center justify-between gap-3 text-xs text-[var(--sf-text-muted)]">
                    <span>{copy.currentSaved}: {stripeSettings.webhookSecretMasked}</span>
                    <button
                      type="button"
                      onClick={() => void clearStripeField("stripe_webhook_secret")}
                      disabled={savingStripe}
                      className="text-[var(--sf-blue-strong)] transition hover:opacity-70 disabled:opacity-50"
                    >
                      {copy.clearSaved}
                    </button>
                  </div>
                )}
                <input
                  type="password"
                  value={stripeDraft.webhookSecret}
                  onChange={(event) => setStripeDraft((prev) => ({ ...prev, webhookSecret: event.target.value }))}
                  placeholder="whsec_..."
                  className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                  {copy.publicUrlLabel}
                </span>
                <input
                  type="url"
                  value={stripeDraft.publicAppUrl}
                  onChange={(event) => setStripeDraft((prev) => ({ ...prev, publicAppUrl: event.target.value }))}
                  placeholder="https://frametale.example.com"
                  className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                />
                <p className="mt-2 text-xs leading-6 text-[var(--sf-text-muted)]">{copy.publicUrlHint}</p>
              </label>

              <button
                type="submit"
                disabled={savingStripe || !stripeDirty}
                className="frametale-primary-button rounded-[1rem] px-5 py-3 text-sm font-semibold transition hover:-translate-y-0.5 disabled:translate-y-0 disabled:opacity-60"
              >
                {savingStripe ? copy.savingStripe : copy.saveStripe}
              </button>
            </form>
          </section>

          <section className="rounded-[1.6rem] border border-[rgba(117,132,159,0.18)] bg-[rgba(248,250,253,0.92)] p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-full bg-[rgba(24,151,214,0.08)] text-[var(--sf-blue)]">
                <Wallet className="h-5 w-5" />
              </div>
              <div>
                <h4 className="text-lg font-semibold text-[var(--sf-text)]">{copy.rechargeTitle}</h4>
                <p className="text-sm text-[var(--sf-text-muted)]">{copy.rechargeBody}</p>
              </div>
            </div>

            <form onSubmit={(event) => void handleSubmit(event)} className="mt-5 space-y-4">
              <label className="block">
                <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                  {copy.userLabel}
                </span>
                <select
                  value={selectedUserId}
                  onChange={(event) => setSelectedUserId(event.target.value)}
                  className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                  required
                >
                  {(overview?.users ?? []).map((user) => (
                    <option key={user.user_id} value={user.user_id}>
                      {user.display_name} ({user.username})
                    </option>
                  ))}
                </select>
              </label>

              <div className="grid gap-4 md:grid-cols-2">
                <label className="block">
                  <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                    {copy.currencyLabel}
                  </span>
                  <select
                    value={currency}
                    onChange={(event) => setCurrency(event.target.value.toUpperCase())}
                    className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                  >
                    <option value="USD">USD</option>
                    <option value="CNY">CNY</option>
                  </select>
                </label>

                <label className="block">
                  <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                    {copy.amountLabel}
                  </span>
                  <input
                    type="number"
                    min="0.0001"
                    step="0.0001"
                    value={amount}
                    onChange={(event) => setAmount(event.target.value)}
                    className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                    required
                  />
                </label>
              </div>

              <label className="block">
                <span className="mb-2 block text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                  {copy.noteLabel}
                </span>
                <input
                  type="text"
                  value={note}
                  onChange={(event) => setNote(event.target.value)}
                  placeholder={copy.notePlaceholder}
                  className="frametale-input w-full rounded-[1rem] px-4 py-3.5 text-[15px] outline-none transition"
                />
              </label>

              {selectedUser && (
                <div className="rounded-[1.1rem] border border-[rgba(117,132,159,0.18)] bg-white/85 px-4 py-3 text-sm text-[var(--sf-text-muted)]">
                  {selectedUser.display_name} ({selectedUser.username}) · {selectedUser.email}
                </div>
              )}

              <button
                type="submit"
                disabled={submitting || !selectedUserId}
                className="frametale-primary-button rounded-[1rem] px-5 py-3 text-sm font-semibold transition hover:-translate-y-0.5 disabled:translate-y-0 disabled:opacity-60"
              >
                {submitting ? copy.submitting : copy.submit}
              </button>
            </form>
          </section>
        </div>

        <section className="space-y-6">
          <div className="rounded-[1.6rem] border border-[rgba(117,132,159,0.18)] bg-[rgba(248,250,253,0.92)] p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-full bg-[rgba(24,151,214,0.08)] text-[var(--sf-blue)]">
                <Webhook className="h-5 w-5" />
              </div>
              <div>
                <h4 className="text-lg font-semibold text-[var(--sf-text)]">{copy.balancesTitle}</h4>
                <p className="text-sm text-[var(--sf-text-muted)]">
                  {checkoutConfig?.enabled ? copy.stripeReady : copy.stripeNotReady}
                </p>
              </div>
            </div>

            {overview?.users.length ? (
              <div className="mt-4 grid gap-4 lg:grid-cols-2">
                {overview.users.map((user) => (
                  <div
                    key={user.user_id}
                    className="rounded-[1.3rem] border border-[rgba(117,132,159,0.18)] bg-white/85 p-4 shadow-[0_18px_40px_rgba(23,38,69,0.04)]"
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <div className="text-base font-semibold text-[var(--sf-text)]">{user.display_name}</div>
                        <div className="mt-1 text-sm text-[var(--sf-text-muted)]">
                          {user.username} · {user.email ?? "-"}
                        </div>
                      </div>
                      <span className="rounded-full bg-[rgba(24,151,214,0.08)] px-2.5 py-1 text-xs font-medium text-[var(--sf-blue-strong)]">
                        {user.role}
                      </span>
                    </div>
                    <div className="mt-4 flex flex-wrap gap-2">
                      {user.balances.length > 0 ? (
                        user.balances.map((balance) => (
                          <span
                            key={`${user.user_id}-${balance.currency}`}
                            className="rounded-full border border-[rgba(117,132,159,0.18)] bg-[rgba(248,250,253,0.92)] px-3 py-1.5 text-sm text-[var(--sf-text)]"
                          >
                            {balance.currency}: {formatMoney(balance.balance, balance.currency, locale)}
                          </span>
                        ))
                      ) : (
                        <span className="text-sm text-[var(--sf-text-muted)]">0</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="mt-4 text-sm text-[var(--sf-text-muted)]">{copy.balancesEmpty}</p>
            )}
          </div>

          <div className="rounded-[1.6rem] border border-[rgba(117,132,159,0.18)] bg-[rgba(248,250,253,0.92)] p-5">
            <h4 className="text-lg font-semibold text-[var(--sf-text)]">{copy.transactionsTitle}</h4>
            {overview?.recent_transactions.length ? (
              <div className="mt-4 space-y-3">
                {overview.recent_transactions.map((tx) => {
                  const isCredit = tx.amount > 0;
                  return (
                    <div
                      key={tx.id}
                      className="flex flex-wrap items-start justify-between gap-4 rounded-[1.2rem] border border-[rgba(117,132,159,0.18)] bg-white/85 px-4 py-3"
                    >
                      <div className="flex min-w-0 items-start gap-3">
                        <div
                          className={`mt-0.5 flex h-9 w-9 items-center justify-center rounded-full ${
                            isCredit ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"
                          }`}
                        >
                          {isCredit ? <ArrowDownLeft className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}
                        </div>
                        <div className="min-w-0">
                          <div className="font-medium text-[var(--sf-text)]">
                            {tx.display_name ?? tx.username ?? tx.user_id}
                          </div>
                          <div className="mt-1 text-sm text-[var(--sf-text-muted)]">
                            {tx.description ?? tx.entry_type}
                          </div>
                          <div className="mt-1 text-xs uppercase tracking-[0.18em] text-[var(--sf-text-soft)]">
                            {tx.entry_type} · {new Date(tx.created_at).toLocaleString()}
                          </div>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className={`text-sm font-semibold ${isCredit ? "text-emerald-700" : "text-amber-700"}`}>
                          {formatSignedAmount(tx, locale)}
                        </div>
                        <div className="mt-1 text-xs text-[var(--sf-text-soft)]">
                          {tx.currency} {formatMoney(tx.balance_after, tx.currency, locale)}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <p className="mt-4 text-sm text-[var(--sf-text-muted)]">{copy.transactionsEmpty}</p>
            )}
          </div>
        </section>
      </div>
    </div>
  );
}
